name-template: "Release to PROD: v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
category-template: $TITLE
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
      - "hotfix"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE #$NUMBER (@$AUTHOR)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes to be released to PRODUCTION

  $CHANGES
