name-template: "Release to UAT"
category-template: $TITLE
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
      - "hotfix"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE #$NUMBER (@$AUTHOR)"
change-title-escapes: '\<*_&'

template: |
  ## Changes to be released to UAT

  $CHANGES
