name: Print value
on:
  release:
    types:
      - "released"
permissions:
  contents: read
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print some values
        shell: bash
        run: |
          echo "print a single variable:"
          echo "${{ github.event.release.target_commitish }}"
        #  echo "print whole github object as json"
        #  echo "${{ toJson(github) }}"